server:
  # `practica` en el 8105 y `solucion` en el 8106.
  port: 8106

spring:
  application:
    name: lab13-empaquetado-solucion

lab13:
  # Valores por defecto. Cada perfil los pisa, y una variable de entorno pisa al perfil.
  saludo: Hola desde el entorno por defecto
  tesoreria-url: http://localhost:9999/tesoreria-falsa

management:
  endpoints:
    web:
      exposure:
        include: health,info
