# =============================================================================
#  auditoria.yml
# =============================================================================
server:
  port: 8233

spring:
  datasource:
    url: jdbc:postgresql://localhost:55482/postgres
    username: postgres
    hikari:
      connection-timeout: 2000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%X{traceId:-........}] AUDITORIA - %msg%n"
