server:
  port: 8095

spring:
  application:
    name: lab09-seguridad

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    locations: classpath:db/migration

lab08:
  jwt:
    secreto: ${LAB08_JWT_SECRETO:clave-de-laboratorio-que-debe-tener-32-bytes-o-mas}

logging:
  level:
    root: WARN
    cl.dgt: INFO
    org.springframework.boot.tomcat: INFO
    org.flywaydb: INFO
