server:
  port: 8095

spring:
  application:
    name: lab09-seguridad

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    locations: classpath:db/migration

lab09:
  jwt:
    secreto: ${LAB09_JWT_SECRETO:clave-de-laboratorio-que-debe-tener-32-bytes-o-mas}
    vigencia-segundos: 1800

logging:
  level:
    root: WARN
    cl.dgt: INFO
    org.springframework.boot.tomcat: INFO
    org.flywaydb: INFO
