server:
  port: 8105

spring:
  application:
    name: lab13-empaquetado

lab12:
  saludo: Hola desde el entorno por defecto
  tesoreria-url: http://localhost:9999/tesoreria-falsa

management:
  endpoints:
    web:
      exposure:
        include: health,info
