-- =============================================================================
--  V3 — La restricción como contrato (Módulo 8)
-- -----------------------------------------------------------------------------
--  La V1 dejó una ausencia DELIBERADA en linea_f29.monto, para agregarla aquí:
--  una migración correctiva es como se ponen contratos a una tabla que ya vive
--  en producción, con datos dentro.
--
--  El contrato: NINGUNA línea vale cero. Cada línea del F29 mueve dinero — un
--  débito (positivo) o un crédito (negativo). Una línea de monto cero no dice
--  nada: es ruido, casi siempre un error de carga. (Ojo: NO es `monto >= 0`. En
--  este dominio los créditos SON negativos —lo documenta LineaF29 y lo prueba
--  Formulario29TotalTest—, así que prohibir el negativo rompería la semilla y la
--  regla RN-06. El contrato correcto no es "no negativo", es "no vacío".)
--
--  ¿Por qué en la base y no solo en Java? Porque Bean Validation protege lo que
--  ENTRA por la API. Pero la tabla la tocan también los scripts, las cargas
--  masivas, el psql de madrugada de un DBA apurado. La última línea de defensa
--  no vive en el framework: vive en el motor. Aquí abajo, el cero es imposible
--  venga de donde venga.
-- =============================================================================
ALTER TABLE linea_f29
    ADD CONSTRAINT ck_linea_f29_monto_no_cero CHECK (monto <> 0);
