server:
  # `practica` en el 8087 y `solucion` en el 8088: pueden correr a la vez.
  port: 8087

spring:
  application:
    name: lab05-relaciones

  jpa:
    hibernate:
      ddl-auto: validate
    # Lo más importante del laboratorio: el SQL que Hibernate escribe por ti.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    root: WARN
    cl.dgt: INFO
    org.springframework.boot.tomcat: INFO
