server:
  port: 8097

spring:
  application:
    name: lab09-resiliencia

lab09:
  tesoreria:
    puerto: 9097

logging:
  level:
    root: WARN
    cl.dgt: INFO
    org.springframework.boot.tomcat: INFO
