server:
  # `practica` en el 8091 y `solucion` en el 8092: pueden correr a la vez.
  port: 8091

spring:
  application:
    name: lab07-concurrencia

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    root: WARN
    cl.dgt: INFO
    org.springframework.boot.tomcat: INFO
